### ISSUE TITLE
Cant add my accessory

### ISSUE THREAD

**Issue by phil71994** [homebridge/HAP-NodeJS#215]
I got an ESP2866 running a sketch from @adysan to control neopixels and a raspberry pi running mosca and HAP-nodeJS. I want to control the pixels using homekit. Everything on the raspberry and the ESP runs fine, the homekit app i have even discovers the node bridge, but when i try to connect to it, it takes about a minute and then gives me the HMError 54. can anybody help me please?

**Comment by KhaosT** [comment]
HMError 54 is HMErrorCodeCommunicationFailure. In this case I assume it's operation timeout... Can you run the hap-nodejs with debug flags and post the output here?

**Comment by phil71994** [comment]
@KhaosT im sorry to say, but i'm a newbie to that. What do i have to do to run it with debug flags?

**Comment by KhaosT** [comment]
Just add ``DEBUG=*`` before the command. like ``DEBUG=* node BridgedCore.js``

**Comment by phil71994** [comment]
root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of                                                                                                                                                              Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                                                             ns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not su                                                                                                                                                             pported (or only supported partially) in the Apple Bonjour compatibility layer o                                                                                                                                                             f Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                                                             ns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Regal_accessory.js
Connecting to MQTT broker...
Regal Connected to MQTT broker
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventedHTTPServer.listen (/usr/local/HAP-NodeJS/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/HAP-NodeJS/lib/HAPServer.js:148:20)
    at Bridge.Accessory.publish (/usr/local/HAP-NodeJS/lib/Accessory.js:435:16)
    at Object.<anonymous> (/usr/local/HAP-NodeJS/BridgedCore.js:33:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
root@HAPnodePi:/usr/local/HAP-NodeJS#

**Comment by KhaosT** [comment]
@phil71994 are you running another instance of hap-nodejs right now? Make sure you kill the old instance and try again.

**Comment by phil71994** [comment]
I rebooted the Pi and checked if NodeBridge was available in the app, it wasnt, so i started HAP-nadejs again with DEBUG and tried connecting and aborted twice, then at the third time i let it go and waited until i got an error in console as you can see:

root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Regal_accessory.js
Connecting to MQTT broker...
Regal Connected to MQTT broker
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [192.168.1.122] New connection from client +6s
  EventedHTTPServer [192.168.1.122] HTTP server listening on port 54826 +19ms
  EventedHTTPServer [192.168.1.122] Client connection closed +3s
  EventedHTTPServer [192.168.1.122] HTTP connection was closed +4ms
  EventedHTTPServer [192.168.1.122] HTTP server was closed +7ms
  EventedHTTPServer [192.168.1.122] New connection from client +5s
  EventedHTTPServer [192.168.1.122] HTTP server listening on port 54826 +8ms
  EventedHTTPServer [192.168.1.122] Client connection closed +22s
  EventedHTTPServer [192.168.1.122] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.1.122] HTTP server was closed +6ms
  EventedHTTPServer [192.168.1.122] New connection from client +10s
  EventedHTTPServer [192.168.1.122] HTTP server listening on port 54826 +4ms
  EventedHTTPServer [192.168.1.122] Client connection closed +1m
  EventedHTTPServer [192.168.1.122] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.1.122] HTTP server was closed +5ms

**Comment by KhaosT** [comment]
@phil71994 it looks HomeKit is having some issue there. Please remove ./persist folder and update the [username](https://github.com/KhaosT/HAP-NodeJS/blob/master/BridgedCore.js#L34) to a different one

**Comment by phil71994** [comment]
i did above steps and it said something like "generating new Homekit info for our server", but i couldnt find any accessories in the app. i restarted the Pi and now i get this:

root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partiall
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Regal_accessory.js
Connecting to MQTT broker...
Regal Connected to MQTT broker
  EventedHTTPServer Server listening on port 51826 +0ms


but i still cant find the NodeBridge in the homekit app

**Comment by phil71994** [comment]
okay i changed back the username to the old one and it shows up again, but i still cant connect

**Comment by KhaosT** [comment]
@phil71994 can you post the log for this time?

**Comment by phil71994** [comment]
here it is. i pressed the Node Bridge again and waited for it to auto-abort:

root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Regal_accessory.js
Connecting to MQTT broker...
Regal Connected to MQTT broker
  Accessory [Node Bridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Node Bridge] Creating new IdentifierCache +78ms
  EventedHTTPServer Server listening on port 51826 +440ms
  EventedHTTPServer [192.168.1.122] New connection from client +7s
  EventedHTTPServer [192.168.1.122] HTTP server listening on port 54826 +13ms
  EventedHTTPServer [192.168.1.122] Client connection closed +1m
  EventedHTTPServer [192.168.1.122] HTTP connection was closed +4ms
  EventedHTTPServer [192.168.1.122] HTTP server was closed +7ms

**Comment by AdySan** [comment]
Since you have only one accessory, it shouldn’t matterwaht username you use. Are you sure you used a HEX string?

Ady

**Comment by phil71994** [comment]
@AdySan  yeah i think so: "CC:22:3D:E3:CE:F6"
its the original one

**Comment by KhaosT** [comment]
@AdySan From his log, it looks like HomeKit isn’t even trying to pair with the accessory. 

@phil71994 this is the log from the session you changed the username and start all over again?

**Comment by phil71994** [comment]
@KhaosT its the log from where i set it back to default since it didnt work when i changed it to something else. i will try "CC:15:3D:E3:CE:F6" now, this is a valid string, am i right?

**Comment by AdySan** [comment]
I don’t understand why changing  the username back to original would make it appear in the app. Perhaps something is persisting ion the phone. Can you also try reseting your home kit config on the phone whenever you delete .persist?

Also, just checking again, you’re on latest iOS version now right?

**Comment by phil71994** [comment]
@AdySan okay i will try that. no i am still on 9.0.2 since i cant go back once i upgrade and i dont want to lose my jailbreak

**Comment by phil71994** [comment]
i changed the username, deleted .persist and reset homekit on the phone. now my phone can see the node Bridge, but still cant connect with the same error

**Comment by KhaosT** [comment]
@phil71994 and can you please attach the log...

**Comment by phil71994** [comment]
root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Regal_accessory.js
Connecting to MQTT broker...
Regal Connected to MQTT broker
  Accessory [Node Bridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Node Bridge] Creating new IdentifierCache +93ms
  EventedHTTPServer Server listening on port 51826 +445ms
  EventedHTTPServer [192.168.1.122] New connection from client +16s
  EventedHTTPServer [192.168.1.122] HTTP server listening on port 54826 +12ms
  EventedHTTPServer [192.168.1.122] Client connection closed +1m
  EventedHTTPServer [192.168.1.122] HTTP connection was closed +5ms
  EventedHTTPServer [192.168.1.122] HTTP server was closed +6ms


its still the same

**Comment by KhaosT** [comment]
@phil71994 alright, for some reasons iOS decides not to pair with the bridge. Can you get the log from iOS device console so we can figure out why this is happening? You can get device log from iOS device using Xcode.

**Comment by phil71994** [comment]
@KhaosT i dont have a mac and therefore i dont have access to xcode

**Comment by phil71994** [comment]
but i have iFile, if you can tell me where those logs are, i can get them

**Comment by KhaosT** [comment]
Aha right, you've access to whole file system ^^ I'm not really sure the full path of the file... try /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/HomeKit.log

**Comment by phil71994** [comment]
This should be the most recent one:

Feb 16 23:05:45.643 homed[341] : Could not remove all accessory keys from controller
Feb 16 23:05:45.905 homed[341] : Successfully fetched record zone, fetching existing records
Feb 16 23:05:46.142 homed[341] : Failed to fetch home data record during initial fetch due to error: domain: CKErrorDomain, code: 11, userInfo = 
	{
	    CKErrorDescription = Error fetching record <CKRecordID: 0x14c5ead60; 84968B22-8974-4102-AAA6-7B9C763A14B5:(HomeDataBlobZone:__defaultOwner__)> from server: Record not found,
	    NSDebugDescription = CKInternalErrorDomain: 2003,
	    NSLocalizedDescription = Error fetching record <CKRecordID: 0x14c5ead60; 84968B22-8974-4102-AAA6-7B9C763A14B5:(HomeDataBlobZone:__defaultOwner__)> from server: Record not found,
	    RequestUUID = 5F90FBA5-73E6-4343-A926-5219D3EA5363,
	    ServerErrorDescription = Record not found,
	}
Feb 16 23:05:46.244 homed[341] : Failed to fetch all records during initial fetch due to error: domain: CKErrorDomain, code: 2, userInfo = 
	{
	    CKErrorDescription = Failed to fetch some records,
	    NSDebugDescription = CKInternalErrorDomain: 1011,
	    NSLocalizedDescription = Failed to fetch some records,
	    RequestUUID = 5F90FBA5-73E6-4343-A926-5219D3EA5363,
	}
Feb 16 23:05:46.252 homed[341] : Marking account is active
Feb 16 23:05:51.690 homed[341] : Accessory manager failed to start discovering accessories for server browser <HAPAccessoryServerBrowserBTLE: 0x1345597f0> with error Error Domain=HMErrorDomain Code=57 "Failed to power on Bluetooth because the Bluetooth is turned off in Settings." UserInfo={NSLocalizedDescription=Failed to power on Bluetooth because the Bluetooth is turned off in Settings.}
Feb 16 23:06:56.086 CoreHAP[341] : 2016-02-16 11:06:56.086149 PM [HTTPClient] ### Timeout on HTTP connection to Node\032Bridge._hap._tcp.local.%9
Feb 16 23:06:56.086 homed[341] : __55-[HAPAccessoryServerIP _continuePairingAfterAuthPrompt]_block_invoke ### Unable to send initial Pair Setup request, received response object: (null), MIME type: Unknown, error: Error Domain=HMErrorDomain Code=54 "Failed with OSStatus code -6722 (kTimeoutErr)" UserInfo={NSLocalizedDescription=Failed with OSStatus code -6722 (kTimeoutErr)}
Feb 16 23:06:56.086 CoreHAP[341] : 2016-02-16 11:06:56.086431 PM [BonjourBrowser] Reconfirming PTR for Node Bridge._hap._tcp.local. on interface 9
Feb 16 23:06:56.087 homed[341] : Failed to add accessory Node Bridge with error: Error Domain=HMErrorDomain Code=54 "Failed with OSStatus code -6722 (kTimeoutErr)" UserInfo={NSLocalizedDescription=Failed with OSStatus code -6722 (kTimeoutErr)}

**Comment by KhaosT** [comment]
This is really strange... HomeKit thought request timeout while there is a connection between iOS device and the bridge. Can you open the url http://{your homebridge ip}:51826/accessories on your iOS device? You should get an error 401.

**Comment by phil71994** [comment]
after about a minute of loading time, i get an error about the server not responding anymore

**Comment by KhaosT** [comment]
Huh, interesting. What about running ``curl http://127.0.0.1:51826/accessories`` on your raspberry pi?

**Comment by phil71994** [comment]
takes about a minute to do something, then i get this:

root@HAPnodePi:/usr/local/HAP-NodeJS# curl http://127.0.0.1:51826/accessories
curl: (7) couldn't connect to host
root@HAPnodePi:/usr/local/HAP-NodeJS#

**Comment by KhaosT** [comment]
then there is something wrong with your node. Can you post result of ``npm version`` here and what's the OS running on Raspberry Pi?

**Comment by phil71994** [comment]
root@HAPnodePi:/usr/local/HAP-NodeJS# npm version
{ 'hap-nodejs': '0.2.2',
  npm: '2.11.2',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.6',
  openssl: '1.0.1o',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

**Comment by KhaosT** [comment]
@phil71994 not really sure why http server won't response... Maybe try to upgrade nodejs to 4.3.0?

**Comment by phil71994** [comment]
could you please instruct me how to do so?

**Comment by KhaosT** [comment]
@phil71994 try following [this](http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/), replace 4.0.0 with 4.3.0

**Comment by phil71994** [comment]
i updated it, node -v gave me 4.3.0, but now i get this:

root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
/usr/local/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

**Comment by phil71994** [comment]
also this when trying to run mosca:

root@HAPnodePi:/usr/local/bin# mosca -v | bunyan
       +++.+++:   ,+++    +++;   '+++    +++.
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +`
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +.
      +`  +.  +: ,+  `+   +'    '+      +   +.
      +`  +.  +: ,+  `+   :+.   '+      +++++.
      +`  +.  +: ,+  `+    ++   '+      +++++.
      +`  +.  +: ,+  `+     ++  '+      +   +.
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +.
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +.
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +.
      +`  +.  +:   +++    +++.   ,++'   +   +.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:1883
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickCallback (node.js:358:17)

**Comment by KhaosT** [comment]
You’ll need to rebuild the modules. run ``npm install`` again should fix this

Best Wishes,
Tian

**Comment by phil71994** [comment]
rebuild took like 20 minutes, but no errors. mosca and HAPnodejs work fine again, but i still get no connection... 

PI log:
root@HAPnodePi:/usr/local/HAP-NodeJS# DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Regal_accessory.js
Connecting to MQTT broker...
Regal Connected to MQTT broker
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [192.168.1.122] New connection from client +10s
  EventedHTTPServer [192.168.1.122] HTTP server listening on port 54826 +21ms
  EventedHTTPServer [192.168.1.122] Client connection closed +1m
  EventedHTTPServer [192.168.1.122] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.1.122] HTTP server was closed +20ms


iPhone log:
Feb 17 00:07:11.723 homed[341] : Could not remove all accessory keys from controller
Feb 17 00:07:11.908 homed[341] : Successfully fetched record zone, fetching existing records
Feb 17 00:07:12.159 homed[341] : Failed to fetch home data record during initial fetch due to error: domain: CKErrorDomain, code: 11, userInfo = 
	{
	    CKErrorDescription = Error fetching record <CKRecordID: 0x14c5849e0; 84968B22-8974-4102-AAA6-7B9C763A14B5:(HomeDataBlobZone:__defaultOwner__)> from server: Record not found,
	    NSDebugDescription = CKInternalErrorDomain: 2003,
	    NSLocalizedDescription = Error fetching record <CKRecordID: 0x14c5849e0; 84968B22-8974-4102-AAA6-7B9C763A14B5:(HomeDataBlobZone:__defaultOwner__)> from server: Record not found,
	    RequestUUID = 48BA903D-EBC9-48AD-81C1-7F2915E8B6C2,
	    ServerErrorDescription = Record not found,
	}
Feb 17 00:07:12.251 homed[341] : Failed to fetch all records during initial fetch due to error: domain: CKErrorDomain, code: 2, userInfo = 
	{
	    CKErrorDescription = Failed to fetch some records,
	    NSDebugDescription = CKInternalErrorDomain: 1011,
	    NSLocalizedDescription = Failed to fetch some records,
	    RequestUUID = 48BA903D-EBC9-48AD-81C1-7F2915E8B6C2,
	}
Feb 17 00:07:12.254 homed[341] : Marking account is active
Feb 17 00:07:36.217 homed[341] : Accessory manager failed to start discovering accessories for server browser <HAPAccessoryServerBrowserBTLE: 0x1345597f0> with error Error Domain=HMErrorDomain Code=57 "Failed to power on Bluetooth because the Bluetooth is turned off in Settings." UserInfo={NSLocalizedDescription=Failed to power on Bluetooth because the Bluetooth is turned off in Settings.}
Feb 17 00:08:39.988 CoreHAP[341] : 2016-02-17 12:08:39.987992 AM [HTTPClient] ### Timeout on HTTP connection to Node\032Bridge._hap._tcp.local.%9
Feb 17 00:08:39.988 homed[341] : __55-[HAPAccessoryServerIP _continuePairingAfterAuthPrompt]_block_invoke ### Unable to send initial Pair Setup request, received response object: (null), MIME type: Unknown, error: Error Domain=HMErrorDomain Code=54 "Failed with OSStatus code -6722 (kTimeoutErr)" UserInfo={NSLocalizedDescription=Failed with OSStatus code -6722 (kTimeoutErr)}
Feb 17 00:08:39.988 CoreHAP[341] : 2016-02-17 12:08:39.988346 AM [BonjourBrowser] Reconfirming PTR for Node Bridge._hap._tcp.local. on interface 9
Feb 17 00:08:39.989 homed[341] : Failed to add accessory Node Bridge with error: Error Domain=HMErrorDomain Code=54 "Failed with OSStatus code -6722 (kTimeoutErr)" UserInfo={NSLocalizedDescription=Failed with OSStatus code -6722 (kTimeoutErr)}

**Comment by KhaosT** [comment]
@phil71994 I'm not really sure why then. @AdySan have you experienced this before?

**Comment by AdySan** [comment]
Nope. i see bluetooth off there not sure why that would cause an issue though.

Perhaps try removing your accessory and try the default ones, just to rule out something wrong in the accessory. Is your RPi ruling anything else on startup that might interfere?

**Comment by AdySan** [comment]
I had issues with pairing before but not sure what iOS ver. could this be due to Home app expecting latest iOS?

**Comment by phil71994** [comment]
He helped me as much as he could, then he pointed me to you to open a new issue.

I know its a lot of work, but if one of you has a raspberry with a working hapnodejs and mosca, could you please send me a working image file of the sd card? I am trying for so long to get this project done and i really dont want to give it up now that it seems so close to finishing :(


_____________________________

**Comment by phil71994** [comment]
Yeah i saw that too, turned it on and it didnt work either. The logs show the same things except for the BT stuff now.

Yeah i could do that, but i'm already in bed now, have to do that tomorrow *sigh*

**Comment by AdySan** [comment]
You’re almost there, have patience! 

My image would have other stuff you don’t want, perhaps first we should rule out other factors like iOS ver, try HAP-NodeJS on the PC, etc.

**Comment by phil71994** [comment]
I dont think so, its a fresh wheezy install, so there should be nothing except for what iwant

**Comment by phil71994** [comment]
I could get a 30pin cable tomorrow to try the newest iOS version on my 4s.

Hap node on pc will most probably be a pain in the ass. And if it works, this is no option as i cant run my pc 24/7

**Comment by KhaosT** [comment]
I believe the issue is on your Raspberry Pi (since curl failed). I’d suggest to try on the PC and if it works then at least we can be sure the problem is on raspberry pi.

Best Wishes,
Tian

**Comment by AdySan** [comment]
curl gives me this https://www.pastery.net/qsduvs/

kind of a dumb question, HAP is actually running in the background when you run curl right?

**Comment by phil71994** [comment]
At first, it wasnt running, but i noticed it myself, started it and ran curl again, with the same result

**Comment by phil71994** [comment]
root@HAPnodePi:/home/pi# DEBUG=* mosca -v | bunyan
       +++.+++:   ,+++    +++;   '+++    +++.
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +`
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +.
      +`  +.  +: ,+  `+   +'    '+      +   +.
      +`  +.  +: ,+  `+   :+.   '+      +++++.
      +`  +.  +: ,+  `+    ++   '+      +++++.
      +`  +.  +: ,+  `+     ++  '+      +   +.
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +.
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +.
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +.
      +`  +.  +:   +++    +++.   ,++'   +   +.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:1883
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickCallback (node.js:358:17)


what happened here @khaosT?

**Comment by AdySan** [comment]
You trying to debug Mosca for some reason?

**Comment by phil71994** [comment]
Yes, because it doesnt work as you see





On Wed, Feb 17, 2016 at 4:45 AM -0800, "Aditya Tannu" <notifications@github.com<mailto:notifications@github.com>> wrote:

You trying to debug Mosca for some reason?

> On Feb 17, 2016, at 3:51 AM, phil71994 <notifications@github.com> wrote:
>
> root@HAPnodePi:/home/pi# DEBUG=* mosca -v | bunyan
> +++.+++: ,+++ +++; '+++ +++.
> ++.+++.++ ++.++ ++,'+ +',++ ++,++
> + +, +: .+ .+ +; +; '+ '+ ++
> ++. +: ,++ ++ +; '+ ;+ + +.
> ++. +: ,++ +' '+ + +.
> ++. +: ,++ :+. '+ +++++.
> ++. +: ,++ ++ '+ +++++.
> ++. +: ,++ ++ '+ + +.
> ++. +: ,++ +: +: '+ ;+ + +.
> ++. +: .+ .+ +; +; '+ '+ + +.
> + +. +: ++;++ ++'++ ++'+' + +.
> +` +. +: +++ +++. ,++' + +.
> events.js:141
> throw er; // Unhandled 'error' event
> ^
>
> Error: listen EADDRINUSE 0.0.0.0:1883
> at Object.exports._errnoException (util.js:870:11)
> at exports._exceptionWithHostPort (util.js:893:20)
> at Server._listen2 (net.js:1237:14)
> at listen (net.js:1273:10)
> at net.js:1382:9
> at nextTickCallbackWith3Args (node.js:452:9)
> at process._tickCallback (node.js:358:17)
>
> what happened here @khaosT?
>
> ?
> Reply to this email directly or view it on GitHub.
>

-

**Comment by AdySan** [comment]
I don’t know any node, but I think that DEBUG = * syntax only applies to HAP-NodeJS not mosca. Even if it does, thats a mosca issue. maybe @mcollina can help with that.

**Comment by mcollina** [comment]
Because of ` Error: listen EADDRINUSE 0.0.0.0:1883`

you have something else running on this system on port 1883. Something like RabbitMQ, Mosquitto or similar.

**Comment by phil71994** [comment]
The mosca issue has resolved itself now

I got my second iphone on iOS 9.2.1 and tried it there, no success. So HAP-NodeJS must be the cause. 

I could (as you guys said) try it on the PC, but I'm too tired atm to try that and if i dont get back my interest, maybe i will dump this project because it just keeps mocking me whenever i try something.

**Comment by AdySan** [comment]
I’d first figure out why curl is not working, the Raspberry is blocking you out for some reason. If it’s hosting a server, it should have access to it. I’ve only tried on Raspbian, not Wheezy, not sure why the would matter though.

Just curious, how are you handling multiple instances of NodeJS apps (mosca and HAP-NodeJS) running on the RPi? You’ve run into ‘another instance of this thing is running in the background’ more than once now. Multiple terminal windows? multiple ssh sessions, Screen, Forever?

**Comment by phil71994** [comment]
@AdiSan i have no idea how i could figure that out to be honest...

I dont really know. When i close the mosca terminal for example, mosca quits, doesn't it? If it doesn't quit, you have your answer there.

**Comment by phil71994** [comment]
Okay guys

@AdySan already heard it, but @KhaosT didn't.

I set everything up freshly and after hours of work, i can finally controll everything by my iphone!

Thank you guys, you helped me so much. 

But i have one final question though: ios9 can communicate with HAP-compatible accessories, even when outside of the wifi. This doesnt work with my setup. Why is that? Is it not even implemented? Or how can i enable it?

**Comment by AdySan** [comment]
You need an Apple TV signed into the same iCloud account on he home wifi network.

**Comment by KhaosT** [comment]
@phil71994 HAP over iCloud is not supported by hap-nodejs. For remote access, you'll have to use Apple TV.

**Comment by phil71994** [comment]
Yeah but since ios8, that doesnt work anymore, at least as far as i read and experienced





On Sun, Feb 21, 2016 at 1:43 PM -0800, "Khaos Tian" <notifications@github.com<mailto:notifications@github.com>> wrote:


@phil71994<https://github.com/phil71994> HAP over iCloud is not supported by hap-nodejs. For remote access, you'll have to use Apple TV.

-

**Comment by KhaosT** [comment]
It works pretty reliable if your Apple TV runs tvOS 9.0 or later…

**Comment by phil71994** [comment]
I just let it be over the night and all of the sudden, it works perfectly :)

I guess this issue can be closed now, thanks again for all your support ;)





On Sun, Feb 21, 2016 at 3:16 PM -0800, "Khaos Tian" <notifications@github.com<mailto:notifications@github.com>> wrote:

It works pretty reliable if your Apple TV runs tvOS 9.0 or later...

Sent from my iPhone

> On Feb 21, 2016, at 2:59 PM, phil71994 <notifications@github.com> wrote:
>
> Yeah but since ios8, that doesnt work anymore, at least as far as i read and experienced
>
>
>
>
>
> On Sun, Feb 21, 2016 at 1:43 PM -0800, "Khaos Tian" <notifications@github.com<mailto:notifications@github.com>> wrote:
>
>
> @phil71994<https://github.com/phil71994> HAP over iCloud is not supported by hap-nodejs. For remote access, you'll have to use Apple TV.
>
> -
> Reply to this email directly or view it on GitHub<https://github.com/KhaosT/HAP-NodeJS/issues/215#issuecomment-186924565>.
> -
> Reply to this email directly or view it on GitHub.
>

-

**Comment by ericklil** [comment]
@KhaosT Change of location breaks the HAP-Node/MQTT/IOS Link?
Having set up HAP-NodeJS in one location with everything working fine. I decided to copy my SD Card from the Raspi and take this to another location. Setting it up as a "Additional Home" in the Homekit configuration.
- The Accessory was not seen until I changed one digit in code 031-45-155 ( note the last digit changed from 4 to 5)
- `BridgedCore.js` (terminal interface) shows that input from IOS is received fine. I have a MQTT connection with an ESP8266 to a light_accessory.js that was working fine
-  The light does not respond to the input from ios-bridgedCore.
-  When I publish the appropriate command directly to the Bridge via `MQTT` lens the unit responds fine...
( I changed the MQTT server address in the `_accessory.js` as well as the `NodeMCU `sketch to refelect the change of networks)
From what I gather is that the IOS and HAP-NodeJS is working  except the connection between the Bridged Core and the MQTT ( both Mosca & BridgedCore Terminal reads are without errors

Any ideas?

**Comment by KhaosT** [comment]
@ericklil If you try to setup another bridge, you need to make sure you use a different username. HomeKit uses username to differentiate bridges. for the part about light doesn't response to the input, I'd suggest you to check your accessory implementation since hap-nodejs was able to forward the command to your accessory.

**Comment by rhardaway** [comment]
I have homekit setup and basically working, my accessory (see attached LED_accessory.js.txt) is supposed to turn an LED connected to the PI on/off, but it doesn't. I can turn the bulb on/off thru a simple python script, so i suspect the Python_Shell command in my example is where the problem is.

I am following the the HomeKit example found here:
     http://www.instructables.com/id/Raspberry-Pi-2-Homekit-from-zero-to-Hey-Siri/

I have Homekit running (DEBUG=* node Core.js) and am using Elgato EVE (2.7.1) to connect. It finds the accessory just find, AND i get the following output in the node log when i turn the light on/off from the app:

Change: 1
  EventedHTTPServer [::ffff:10.0.0.176] Muting event '1.9' notification for this connection since it originated here. +74ms
  EventedHTTPServer [::ffff:10.0.0.176] HTTP Response is finished +3ms
On Success
  EventedHTTPServer [::ffff:10.0.0.176] HTTP request: /characteristics +4s
  HAPServer [B8:27:EB:33:CB:28] HAP Request: PUT /characteristics +2ms
  Accessory [Light 1] Processing characteristic set: [{"aid":1,"iid":9,"value":0}] +2ms
  Accessory [Light 1] Setting Characteristic "Turn On the Light" to value 0 +2ms
Change: 0
  EventedHTTPServer [::ffff:10.0.0.176] Muting event '1.9' notification for this connection since it originated here. +28ms
  EventedHTTPServer [::ffff:10.0.0.176] HTTP Response is finished +3ms
Off Success
  EventedHTTPServer [::ffff:10.0.0.176] HTTP request: /characteristics +2s
  HAPServer [B8:27:EB:33:CB:28] HAP Request: PUT /characteristics +1ms
  Accessory [Light 1] Processing characteristic set: [{"aid":1,"iid":9,"value":1}] +3ms
  Accessory [Light 1] Setting Characteristic "Turn On the Light" to value 1 +1ms
[LED_accessory.js.txt](https://github.com/KhaosT/HAP-NodeJS/files/938829/LED_accessory.js.txt)

  thanks, bob

**Comment by NorthernMan54** [comment]
Bob,

Have you tried posting your issue with the instructable author?

Just looking at the log and HAP-NodeJS is receiving the on/off command successfully, so the problem would be in your accessory.

Sean

**Comment by rhardaway** [comment]
I will do that Sean, as with a little more investigation i discovered the problem is with the Python_shell code in the accessory. You have to specify a path to the py scripts you want to run, the example simply says:

		PythonShell.run('light1.py', function (err) { 

and thus the light1.py script is not found. You can’t just specify a qualified path either, you need to create and pass in a options structure:

	var options = {
 		 mode: 'text',
  		scriptPath: '/home/pi/HAP-NodeJS/python'
	};

and then:

	PythonShell.run('light1.py', options, function (err) {

thanks, bob

Robert Hardaway
robert.hardaway@gmail.com
303.717.8993
