### ISSUE TITLE
Discussion: Next-Gen HomeKit (iOS 14, iPadOS 14, macOS 11, tvOS 14)

### ISSUE THREAD

**Issue by Supereg** [homebridge/HAP-NodeJS#832]
This issue should be used for any discussion regarding the latest changes (or problems) in HomeKit with the release of the first beta version for iOS 14, iPadOS 14, macOS 11 and tvOS 14.

I just know released [v0.7.5](https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.7.5) of hap-nodejs containing all newly added service and characteristics definitions.
I also shared my [first speculations](https://twitter.com/herrsupereg/status/1275210584548691969?s=21) about some of the new services.

Feel free to share anything you think would be useful to the community.

~ Andi

**Comment by bonexd** [comment]
Just an idea, don't know if its possible but with the implementation of the carkey in iOS 14, i wonder if it were possible to use something to create a custom carkey for any car, like an nfc tag or something, i would have doubts about its security but it _could_ be possible.

**Comment by bonexd** [comment]
iOS 14 also messed with the way that motion sensors are handled, so anything you have listed as a motion sensor might still work but they don't show as the original name you would have had, they just show as "Motion Sensor", going into the sensor however you still get the stats and name you used to have. Mine seems to have an issue where its stuck on 100% when it should be on 0% right now so i cant really confirm much about their functionality at the time being.
 
![image](https://user-images.githubusercontent.com/35059872/85393646-af593a80-b590-11ea-8508-ded7d5adf4b4.png)
![image](https://user-images.githubusercontent.com/35059872/85393711-c730be80-b590-11ea-90e3-32c9a6da5c85.png)

**Comment by Zer0x00** [comment]
Is it possible to find out where you got the information about the upcoming characteristics?

I would also like to know if there is a sample implementation for [Characteristic Value Transition Control](https://developers.homebridge.io/#/characteristic/CharacteristicValueTransitionControl) since the data type is tlv8.

**Comment by Supereg** [comment]
> I would also like to know if there is a sample implementation for Characteristic Value Transition Control since the data type is tlv8.

The format is currently unknown. We may be able to get the format when looking at the homed binary or we just wait for an accessory to appear, which supports this functionality.

**Comment by longzheng** [comment]
iOS 14 Home app seems to not want to display light sensors anymore in either the favourites or even the room. 

For example I have two light sensors created via homebridge but they don’t appear in my room.

![image](https://user-images.githubusercontent.com/484912/85820216-1b1dec00-b7b9-11ea-9c6c-702598de8153.png)

However the sensors do exist in my Home settings > Hubs and Bridges > Homebridge > Accessories.

![image](https://user-images.githubusercontent.com/484912/85820221-1f4a0980-b7b9-11ea-868d-b18170fdc3b8.png)

![image](https://user-images.githubusercontent.com/484912/85820226-21ac6380-b7b9-11ea-992b-1649fb30271c.png)

This is what it looks like on a iOS 13 device

![image](https://user-images.githubusercontent.com/484912/85820305-4c96b780-b7b9-11ea-9a4e-337ad57f5511.jpeg)

**Comment by n0rt0nthec4t** [comment]
@longzheng I like you're method for capturing a solar invertor.. I went the otherway with my SolarEdge on and created a power point with battery service attached

![IMG_2093](https://user-images.githubusercontent.com/19759130/86066526-b2cf5300-bab5-11ea-9d9c-73a442c26f27.png)
![IMG_2094](https://user-images.githubusercontent.com/19759130/86066534-b95dca80-bab5-11ea-9c24-0f42694e4a71.png)

If powerpoint is ON, means solar is generating
Battery percentage is how much solar vs max capacity is being generated
Charging is if sending to grid or not

**Comment by n0rt0nthec4t** [comment]
Seems in with a valve/sprinkler default duration, the default running time list is missing all entries eg:

iOS 14:

![IMG_0909](https://user-images.githubusercontent.com/19759130/87887189-461cf800-ca66-11ea-938c-3f898647c1b3.jpeg)

iOS 13:

![Screen Shot 2020-07-20 at 8 51 28 am](https://user-images.githubusercontent.com/19759130/87887210-6d73c500-ca66-11ea-863e-cde093b6493c.png)

**Comment by popepay** [comment]
Anyone else having issues with the doorbells notifications on Apple TVs (tvOS14)? 
It worked when I tried it initially on beta 1, but I don't think I've seen it work since (I'm now on beta 3). 

Setup: Nest Hello > homebridge-nest-cam > homekit > iOS14 / tvOS14

**Comment by hugozheng2017** [comment]
> iOS 14 Home app seems to not want to display light sensors anymore in either the favourites or even the room.
> 
> For example I have two light sensors created via homebridge but they don’t appear in my room.
> 
> ![image](https://user-images.githubusercontent.com/484912/85820216-1b1dec00-b7b9-11ea-9c6c-702598de8153.png)
> 
> However the sensors do exist in my Home settings > Hubs and Bridges > Homebridge > Accessories.
> 
> ![image](https://user-images.githubusercontent.com/484912/85820221-1f4a0980-b7b9-11ea-868d-b18170fdc3b8.png)
> 
> ![image](https://user-images.githubusercontent.com/484912/85820226-21ac6380-b7b9-11ea-992b-1649fb30271c.png)
> 
> This is what it looks like on a iOS 13 device
> 
> ![image](https://user-images.githubusercontent.com/484912/85820305-4c96b780-b7b9-11ea-9a4e-337ad57f5511.jpeg)
> 
> EDIT: I've since refactored my plugin to use a lightbulb with a light sensor and it appears if I tap open the light https://github.com/longzheng/homebridge-fronius-inverter-lights



> iOS 14 Home app seems to not want to display light sensors anymore in either the favourites or even the room.
> 
> For example I have two light sensors created via homebridge but they don’t appear in my room.
> 
> ![image](https://user-images.githubusercontent.com/484912/85820216-1b1dec00-b7b9-11ea-9c6c-702598de8153.png)
> 
> However the sensors do exist in my Home settings > Hubs and Bridges > Homebridge > Accessories.
> 
> ![image](https://user-images.githubusercontent.com/484912/85820221-1f4a0980-b7b9-11ea-868d-b18170fdc3b8.png)
> 
> ![image](https://user-images.githubusercontent.com/484912/85820226-21ac6380-b7b9-11ea-992b-1649fb30271c.png)
> 
> This is what it looks like on a iOS 13 device
> 
> ![image](https://user-images.githubusercontent.com/484912/85820305-4c96b780-b7b9-11ea-9a4e-337ad57f5511.jpeg)
> 
> EDIT: I've since refactored my plugin to use a lightbulb with a light sensor and it appears if I tap open the light https://github.com/longzheng/homebridge-fronius-inverter-lights

it is fixed in iOS 14 Beta 6

**Comment by n0rt0nthec4t** [comment]
Ok, so not sure if its a issue with HAP-Nodejs now that ISO 14 has gone public, but still have the issue where the default runtime list for valves is missing entries.. IS this something we now have to code in correctly? Might do some playing with the accessory simulator and a dummy accessory in HAP when I get some time to see what's what, but will just ask here first

**Comment by n0rt0nthec4t** [comment]
OK, so using the HomeKit simulator, it seems it only provides a 5 and 10min option in the runtime default list.. Unsure how to add new entries.

**Comment by friartuck6000** [comment]
Re: the new lightbulb characteristics:

> The format is currently unknown. We may be able to get the format when looking at the homed binary or we just wait for an accessory to appear, which supports this functionality.

Have there been any leads on this at all?

**Comment by n0rt0nthec4t** [comment]
> OK, so using the HomeKit simulator, it seems it only provides a 5 and 10min option in the runtime default list.. Unsure how to add new entries.

Ok, so cannot get the list populate using setProps with valid values.. 

Anyone have any thoughts on getting the runtime list populated for valves? (SetDuration characteristic) Definitely a regression from iOS 13 -> 14. Still exists in iOS 14.2b

**Comment by Supereg** [comment]
As iOS 14 is released to the public and the beta phase is pretty much over this issue will be closed.
